<a href="https://colab.research.google.com/github/jarifNmohsin/Pytorch-Colab/blob/main/intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [5]:
import torch
import numpy as np

# LISTS

In [9]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS


In [12]:
np1 = np.random.rand(3,4)
np1

array([[0.17655849, 0.00786732, 0.99034514, 0.98865519],
       [0.91521224, 0.62447084, 0.82587244, 0.06240662],
       [0.98937522, 0.79178393, 0.09658006, 0.14930586]])

In [13]:
np1.dtype

dtype('float64')

# TENSORS


In [15]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.2781, -0.3971, -0.0502,  0.5223],
        [-0.0607,  1.9040, -0.1664,  0.3676],
        [-1.8890,  0.6975,  1.9230, -1.0863]])

In [16]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1766, 0.0079, 0.9903, 0.9887],
        [0.9152, 0.6245, 0.8259, 0.0624],
        [0.9894, 0.7918, 0.0966, 0.1493]], dtype=torch.float64)