<a href="https://colab.research.google.com/github/jarifNmohsin/Pytorch-Colab/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [8]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [9]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [10]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [11]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
# Subtraction Longhand
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [13]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Div Longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [19]:
# Remainder Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [22]:
# Reassignment_
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([ 6,  8, 10, 12])